apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools-deployment
  namespace: default
  labels:
    type: IoT
    pod: it-tools
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: it-tools
  template:
    metadata:
      labels:
        pod: it-tools
    spec:
      containers:
        - image: corentinth/it-tools:latest
          name: it-tools
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools-service
  namespace: default
  labels:
    type: IoT
    pod: it-tools
spec:
  type: ClusterIP
  selector:
    pod: it-tools
  ports:
    - port: 80
      targetPort: 80
