version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`docker.lilay.dev`)
        - traefik.http.routers.frontend.entrypoints=https
        - traefik.http.services.frontend.loadbalancer.server.port=9000
        - traefik.http.routers.frontend.service=frontend
        - traefik.http.routers.frontend.tls.certresolver=cloudflare

volumes:
  data:

networks:
  proxy:
    external: true