apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: IoT
    pod: n8n
  name: n8n-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: IoT
    pod: n8n
  name: n8n-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: IoT
    pod: n8n
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        pod: n8n
    spec:
      containers:
        - env:
            - name: GENERIC_TIMEZONE
              value: Asia/Phnom_Penh
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_HOST
              value: n8n.lilay.dev
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: NODE_ENV
              value: production
            - name: TZ
              value: Asia/Phnom_Penh
            - name: WEBHOOK_URL
              value: https://n8n.lilay.dev/
          image: docker.n8n.io/n8nio/n8n
          name: n8n
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-data
            - mountPath: /files
              name: n8n-files
      restartPolicy: Always
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
        - name: n8n-files
          persistentVolumeClaim:
            claimName: n8n-files
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: IoT
    pod: n8n
  name: n8n-service
spec:
  type: ClusterIP
  selector:
    pod: n8n
  ports:
    - port: 5678
      targetPort: 5678
