apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data
  labels:
    type: IoT
    pod: searxng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng-deployment
  labels:
    type: IoT
    pod: searxng
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: searxng
  template:
    metadata:
      labels:
        pod: searxng
    spec:
      containers:
        - image: docker.io/searxng/searxng:latest
          name: searxng
          ports:
            - containerPort: 8080
          env:
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  name: searxng-key
                  key: secret_key
          volumeMounts:
            # Mounts the cache/data to the persistent volume
            - name: data-volume
              mountPath: /var/cache/searxng
            # Mounts a config map (see note below)
            - name: config-volume
              mountPath: /etc/searxng
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: searxng-data
        - name: config-volume
          configMap:
            name: searxng-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: searxng-service
  labels:
    type: IoT
    pod: searxng
spec:
  type: ClusterIP
  selector:
    pod: searxng
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  labels:
    type: IoT
    pod: searxng
data:
  settings.yml: |
    use_default_settings: true
    general:
      debug: false
    search:
      safe_search: 0
      formats:
        - html
        - json
