services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
    #   - 8000:8000  # Remove if you do not intend to use Edge Agents

    networks:
      - proxy

volumes:
  portainer_data:
    name: portainer_data

networks:
  proxy:
    external: true
