---
secrets:
  cf_token:
    external: true

services:
  traefik:
    image: traefik:v3.4.1
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - proxy
    environment:
      CF_DNS_API_TOKEN: /run/secrets/cf_token
    volumes:
      - "./data/traefik.yml:/traefik.yml:ro"
      - "./data/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    secrets:
      - cf_token
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.125"
          memory: 64M
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
